// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sum.proto

package com.sumservice;

public interface SumRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SumRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated int32 numbers = 1;</code>
   * @return A list containing the numbers.
   */
  java.util.List<java.lang.Integer> getNumbersList();
  /**
   * <code>repeated int32 numbers = 1;</code>
   * @return The count of numbers.
   */
  int getNumbersCount();
  /**
   * <code>repeated int32 numbers = 1;</code>
   * @param index The index of the element to return.
   * @return The numbers at the given index.
   */
  int getNumbers(int index);
}
