// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sum.proto

package com.sumservice;

public final class SumServiceProto {
  private SumServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SumRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SumRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SumResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SumResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tsum.proto\"\035\n\nSumRequest\022\017\n\007numbers\030\001 \003" +
      "(\005\"\035\n\013SumResponse\022\016\n\006result\030\001 \001(\00523\n\nSum" +
      "Service\022%\n\010SumArray\022\013.SumRequest\032\014.SumRe" +
      "sponseB#\n\016com.sumserviceB\017SumServiceProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SumRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SumRequest_descriptor,
        new java.lang.String[] { "Numbers", });
    internal_static_SumResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SumResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SumResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
